version: '3'

services:
  client:
    image: rsalian/centos-sshpass
    volumes:
      - workingdir:/workingdir
      - localkey:/local
      - host1ssh:/host1
      - names:/names
      - ./test.sh:/test.sh
    links:
      - "piper:piper"
      - "piper_mysql:piper_mysql"
    command:
      - "/bin/bash"
      - "/test.sh"
    depends_on:
      - piper
      - piper_mysql
  host1:
    image: rastasheep/ubuntu-sshd
    volumes:
      - host1ssh:/root/.ssh
      - names:/names
  host2:
    image: rastasheep/ubuntu-sshd
    volumes:
      - names:/names
  piper:
    environment:
      - "SSHPIPERD_UPSTREAM_WORKINGDIR_NOCHECKPERM=true"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
    volumes:
      - workingdir:/var/sshpiper
      - ./piper.sh:/piper.sh
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - host1
      - host2
  piper_mysql:
    environment:
      - "SSHPIPERD_UPSTREAM_DRIVER=mysql"
      - "SSHPIPERD_UPSTREAM_MYSQL_HOST=mysql"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
      - "mysql:mysql"
    volumes:
      - ./piper.sh:/piper.sh
      - workingdir:/var/sshpiper
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - mysql
      - host1
      - host2
  mysql:
    image: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=sshpiper"
    tmpfs:
      - /var/lib/mysql


volumes:
  workingdir:
  localkey:
  host1ssh:
  names:
